import Head from "next/head";
import React, { useState, useEffect } from "react";
import { v4 as uuidv4 } from "uuid";

import styles from "../styles/Home.module.css";
import Form from "../components/Form";
import Todos from "../components/Todos";
import useStorage from "../other/useStorage";

export type TodoType = [string, boolean, string];
export type TodosType = TodoType[];

export default function Home({}) {
  const [todos, setTodos] = useState<TodosType>([]);
  const [title, setTitle] = useState("");
  const { getItem, setItem, removeItem } = useStorage();

  useEffect(() => {
    const data = getItem("todos");
    if (data !== undefined) {
      setTodos(JSON.parse(data));
    }
  }, []);

  useEffect(() => {
    setItem("todos", JSON.stringify(todos));
  }, [todos]);

  function toggleTodo(key: string) {
    setTodos((todos) =>
      todos.map((todo) => {
        if (todo[2] == key) todo[1] = !todo[1];
        return todo;
      })
    );
  }

  function removeTodo(key: string) {
    setTodos((todos) => todos.filter((todo) => todo[2] != key));
  }

  function removeTodos() {
    removeItem("todos");
    setTodos([]);
  }

  function addTodo(todo: string) {
    if (todo.length == 0 || todo.length >= 12 || todo[0] == " ") return;
    setTodos([...todos, [todo, false, uuidv4()]]);
    setTitle("");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Todo app</h1>

        <button onClick={removeTodos}>Clear</button>

        <Form title={title} setTitle={setTitle} addTodo={addTodo} />
        {todos != [] && (
          <Todos
            removeTodo={removeTodo}
            toggleTodo={toggleTodo}
            todos={todos}
          />
        )}
      </main>
    </div>
  );
}
